import { useState } from "react";
import { useNavigate } from "react-router-dom";
import "./Glossary.css";

const glossaryData = [
  {
    term: "Astronomical Image",
    definition:
      "A digital representation of electromagnetic radiation from celestial objects recorded by a telescope and detector.",
  },
  {
    term: "Image Processing",
    definition:
      "Computational techniques used to enhance, analyze, and extract information from digital images.",
  },
  {
    term: "Preliminary Analysis",
    definition:
      "The initial examination and correction of raw astronomical data before advanced scientific analysis.",
  },
  {
    term: "CCD (Charge-Coupled Device)",
    definition:
      "A highly sensitive electronic detector commonly used in astronomical imaging.",
  },
  {
    term: "CMOS Sensor",
    definition:
      "A digital imaging sensor used in astronomy, known for low power consumption and fast readout.",
  },
  {
    term: "Signal-to-Noise Ratio (SNR)",
    definition:
      "A measure comparing the strength of the astronomical signal to background noise.",
  },
  {
    term: "Noise",
    definition:
      "Random variations in image data caused by physical, electronic, or environmental factors.",
  },
  {
    term: "Bias Frame",
    definition:
      "A calibration image used to remove electronic offset from raw images.",
  },
  {
    term: "Dark Frame",
    definition:
      "A calibration image that accounts for thermal noise generated by the detector.",
  },
  {
    term: "Flat-Field Image",
    definition:
      "A calibration frame used to correct pixel-to-pixel sensitivity variations.",
  },
  {
    term: "Photometry",
    definition:
      "The measurement of the brightness (flux) of astronomical objects.",
  },
  {
    term: "Aperture Photometry",
    definition:
      "A method of measuring brightness by summing pixel values within a fixed aperture.",
  },
  {
    term: "PSF (Point Spread Function)",
    definition:
      "A mathematical description of how a point source appears in an image.",
  },
  {
    term: "PSF Fitting Photometry",
    definition:
      "A photometric technique that models stellar images using the PSF, effective in crowded fields.",
  },
  {
    term: "Crowded Field",
    definition:
      "A region of the sky containing a high density of overlapping astronomical sources.",
  },
  {
    term: "ALLSTAR",
    definition:
      "A software program used for PSF fitting photometry in dense stellar fields.",
  },
  {
    term: "DAOPHOT",
    definition:
      "A photometry software package for detecting and measuring stars in crowded images.",
  },
  {
    term: "Sharpness",
    definition:
      "A diagnostic parameter indicating whether an object is point-like or extended.",
  },
  {
    term: "Chi-Square (χ²)",
    definition:
      "A statistical measure used to evaluate the quality of a model fit to data.",
  },
  {
    term: "Background Estimation",
    definition:
      "The process of measuring and subtracting sky and instrumental background from images.",
  },
  {
    term: "Source Detection",
    definition:
      "The identification of astronomical objects within an image.",
  },
  {
    term: "Astrometry",
    definition:
      "The precise measurement of positions and motions of celestial objects.",
  },
  {
    term: "Image Registration",
    definition:
      "The alignment of multiple images of the same sky region.",
  },
  {
    term: "Image Stacking",
    definition:
      "Combining multiple images to improve signal-to-noise ratio.",
  },
  {
    term: "GALFIT",
    definition:
      "A software tool for two-dimensional parametric modeling of galaxy images.",
  },
  {
    term: "Sérsic Profile",
    definition:
      "A mathematical function describing the surface brightness distribution of a galaxy.",
  },
];

const Glossary = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const navigate = useNavigate();

  const filteredGlossary = glossaryData.filter((item) =>
    item.term.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="glossary-container">
      <button className="back-button" onClick={() => navigate(-1)}>
        &larr; Back
      </button>
      <h1 className="glossary-title">Glossary</h1>
      <input
        type="text"
        className="glossary-search"
        placeholder="Search terms..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
      />
      <div className="glossary-list">
        {filteredGlossary.map((item, index) => (
          <div key={index} className="glossary-item">
            <h3 className="term">{item.term}</h3>
            <p className="definition">{item.definition}</p>
          </div>
        ))}
        {filteredGlossary.length === 0 && (
          <p className="no-results">No results found.</p>
        )}
      </div>
    </div>
  );
};

export default Glossary;
